[project]
name = "commandgenie"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "llama-cpp-python>=0.3.8",
    "typer>=0.15.3",
]
